# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
  branches:
    include:
    - main
    - master
    - develop
    - release/*
  paths:
    exclude:
    - README.md
    - docs/*

pool:
    vmImage: 'windows-latest'

variables:
  solution: 'BehaviorTreeForTests/BehaviorTreeForTests.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  releaseBuildNumber: '1.0.0'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  
- task: UseDotNet@2
  displayName: 'Use .NET 8.x'
  inputs:
    packageType: 'sdk'
    version: 8.x
  continueOnError: true

- task: Bash@3
  displayName: Restore nuget
  inputs:
    targetType: 'inline'
    script: dotnet restore $(solution)
  
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudV2'
    organization: 'stanislau'
    scannerMode: 'MSBuild'
    projectKey: 'Stanislau_behavior-tree-for-testing'
    projectName: 'behavior-tree-for-testing'
    extraProperties: |
        sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)\BehaviorTreeForTests.Tests\coverage.opencover.xml
        sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)\*.trx

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/BehaviorTreeForTests.Tests.csproj'
    publishTestResults: true
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true "/p:CoverletOutputFormat=\"opencover,Cobertura\""'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage result'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/*.cobertura.xml'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
 
